export  enum ConnectorName {
    Sqlserver="Microsoft SQL Server",
    DBConnector="DBConnectorCredentials",
    FilesName="FileComponent",
    SocialMedia="Socialmedia",
    MySQL="My SQL",
    OracleDBMS="Oracle DBMS",
    MongoDB ="MongoDB",
    PostgreSQL="Postgre SQL",
    MicrosoftAccess="Microsoft Access",
    ElasticDB="Elastic DB",
    CassandraDB="Cassandra DB",
    CosmosDB="Cosmos DB",
    Redis="Redis",
    AmazonDynamoDB="Amazon DynamoDB",
    AmazonRedshift="Amazon Redshift",
    MicrosoftAzure="Microsoft Azure",
    GoogleBigQuery="Google BigQuery",
    Snowflake="Snowflake",
    MicroFocusVertica="MicroFocus Vertica",
    AmazonRDS="Amazon RDS",
    MariaDB="MariaDB",
    IBMDb2="IBM Db2",
    OracleAutonomous="Oracle Autonomous",
    MarkLogic="MarkLogic",
    //Files key with Value
    CSVFile="CSV File",
    XMLFile="XML File",
    JSONFile="JSON File",
    PDFFile="PDF File",
    ZipFil="Zip Fil",
    MicrosoftExcel="Microsoft Excel",
    GoogleSheet="Google Sheet",
    OpenOffice="Open Office",
    ODSFile="ODS File",
    FTPServer="FTP Server",
    SFTPServer="SFTP Server",
    Dropbox="Dropbox",
    GoogleDrive="Google Drive",
    MicrosoftOneDrive="Microsoft OneDrive",
    OneHub="OneHub",
    Box="Box",
    EgnyteUSA="Egnyte USA",
    MASV="MASV",
    eFileCabinet="eFile Cabinet",
    iDrive="iDrive",
    Wire="Wire",
    MEGA="MEGA",
    ApacheHDFS="Apache HDFS",
    Azurefile="Azure file",
    AmazonS3="Amazon S3",
    GoogleCloud="Google Cloud",
    WeTransfe="We Transfe",
    SendAnywheree="Send Anywhere",
    EmailAttachment="Email Attachment",
    Hightail="Hightail",
    Slack="Slack",
    //social Media
    FacebookPublicPage="Facebook Public Page",
    }
    export  enum Extractdesionmaking {
        Sqlserver="Microsoft SQL Server",
        CSVFile="CSV File",

        }